GET https://viacep.com.br/ws/01001000/json HTTP/1.1
Content-Type: application/json

###

GET http://localhost:3005/api/zipcodes?zipcode=01001000 HTTP/1.1
Content-Type: application/json
Authorization: Basic YWRtaW46MTIzNA==

###

GET http://localhost:3005/api/products HTTP/1.1
Content-Type: application/json
Authorization: Basic YWRtaW46MTIzNA==

###

GET http://localhost:3005/api/products/5244d9a8-5edf-4459-92dd-5ca5c056202d HTTP/1.1
Content-Type: application/json
Authorization: Basic YWRtaW46MTIzNA==

###

POST http://localhost:3005/api/products HTTP/1.1
Content-Type: application/json
Authorization: Basic YWRtaW46MTIzNA==

{
	"name": "DDDD",
	"description": "...",
	"quantity": 31,
	"price": 7.80,
	"active": false
}

###

PUT http://localhost:3005/api/products/5244d9a8-5edf-4459-92dd-5ca5c056202d HTTP/1.1
Content-Type: application/json
Authorization: Basic YWRtaW46MTIzNA==

{
	"quantity": 88
}

###

DELETE http://localhost:3005/api/products/5244d9a8-5edf-4459-92dd-5ca5c056202d HTTP/1.1
Content-Type: application/json
Authorization: Basic YWRtaW46MTIzNA==
