FROM golang:1.22.2 as Builder
WORKDIR /src
COPY . /src
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o binary-of-app cmd/main.go

FROM busybox:1.36.1
WORKDIR /src
COPY --from=Builder /src/binary-of-app /src
CMD ["/src/binary-of-app"]
EXPOSE 8080
