FROM golang:1.22.2
RUN curl -sL https://deb.nodesource.com/setup_20.x | bash && apt-get install -y nodejs && node -v && npm -v && npm install -g nodemon@3.1.0
RUN curl -fsSL https://raw.githubusercontent.com/pressly/goose/v3.19.2/install.sh | bash -s v3.19.2 && goose -version
WORKDIR /app
COPY . /app
EXPOSE 80
